Algorithms
robinho1989/Sorting-Algorithms-in-Javascript pull request #5
Opened 2022-03-22 20:13 UTC by robinho1989

2022-03-24 19:02 UTC, patryk-bernasiewicz requested changes
Świetnie radzisz sobie z BEM, ale zalecam nieco luźniejsze podejście do rozbijania sekcji na mniejsze elementy :) Zawsze jest lepiej mieć o jeden blok więcej, niż męczyć się z wymyślaniem kolejnych członów dla nazw elementów.

2022-03-24 19:02 UTC, patryk-bernasiewicz commented on algorithms.html
> +                    <li class="navbar__list-item"><a href="algorithm.html" class="navbar__list-link">Algorithm</a></li>
nieprawidłowy link - plik nazywa się algorithm`s`.html

2022-03-24 19:02 UTC, patryk-bernasiewicz commented on algorithms.html
> +                            <a href="#start" class="algorithm__btn algorithm__btn--start">start</a>
Tak naprawdę przyciski w tej sekcji byłyby przyciskami interaktywnymi, nie linkami. Linki stosujemy tylko i wyłącznie wtedy, gdy chcemy, aby coś przenosiło na inną stronę, w tym przypadku natomiast lepiej sprawdzi się zwykły `<button>`.

2022-03-24 19:02 UTC, patryk-bernasiewicz commented on algorithms.html
> +                        <div class="algorithm__btn-container">
Nie jestem przekonany, czy `btn-container` to dobra nazwa dla tego elementu bloku. Być może coś w stylu `algorithm__menu` albo `algorithm__options`?

2022-03-24 19:02 UTC, patryk-bernasiewicz commented on algorithms.html
> +                    <h3 class="algorithm__coding-box-title">Code</h3>
Zauważ, jak dużo musisz tutaj stosować nazw, żeby określić pod-elementy :) Być może warto byłoby wydzielić kawałek z tego kodu i zrobić z niego osobny blok z jego własnymi elementami?

2022-03-24 19:02 UTC, patryk-bernasiewicz commented on algorithms.html
> +            <img src="/img/footer-logo.svg" alt="Website logo" class="footer__logo">
ścieżka absolutna do pliku

2022-03-24 20:19 UTC, robinho1989 commented on algorithms.html
> +                    <li class="navbar__list-item"><a href="algorithm.html" class="navbar__list-link">Algorithm</a></li>
Zgadzam się, tutaj niestety wkradł się chochlik ;)

2022-03-24 20:19 UTC, robinho1989 commented on algorithms.html
> +                            <a href="#start" class="algorithm__btn algorithm__btn--start">start</a>
Zmienione.

2022-03-24 20:22 UTC, robinho1989 commented on algorithms.html
> +                        <div class="algorithm__btn-container">
W sumie masz rację, bardziej logiczną nazwą tego elementu będzie `algorithm__options`. W wypadku późniejszych zmian łatwo będę mógł zlokalizować ten element po nazwie ;)

2022-03-24 20:24 UTC, robinho1989 commented on algorithms.html
> +                    <h3 class="algorithm__coding-box-title">Code</h3>
Stworzyłem osobny blok o nazwie `coding-box`. Musze zacząć dzielić kod na większą ilość bloków, znacznie ułatwia to tak prostą czynność jak nazywanie klas. A poza tym to nie tworzę tasiemców :P

2022-03-24 20:24 UTC, robinho1989 commented on algorithms.html
> +            <img src="/img/footer-logo.svg" alt="Website logo" class="footer__logo">
Poprawione.

2022-03-25 13:22 UTC, patryk-bernasiewicz approved these changes

2022-03-25 21:18 UTC, closed without merging